### PR TITLE
chore: release v0.3.0

### PR DESCRIPTION
**Pull request by lidel**
- [x] #72 
- [x] #74 
- [x] #73 
- [x] changelog
- [x] version.json

### CODE REVIEW

**Comment by lidel** [comment]
Seems that goreleaser CI job checks [failed due to Github API quota](https://github.com/ipfs/someguy/actions/runs/9653282596/job/26625232649?pr=76#step:6:42), and it is probably also why we had panic in comment above:

```
RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID  [..]
```

I'll retry later today / tomorrow.

**Comment by lidel** [comment]
cc @ipfs/ipdx for visibility:  I imagine the panic in the `gorelease` above is due to github API limits error and missing error handling. My plan is to re-run in a few hours, but lmk if this looks familiar or is something else.

**Comment by galargh** [comment]
I created an issue for handling the secondary rate limits - https://github.com/ipdxco/unified-github-workflows/issues/70

As for the `gorelease` output, that seems to be connected to the binary being released itself, isn't it?

**Comment by lidel** [comment]
Did some digging, the job uses old version of `gorelease` (hardcoded to version [golang.org/x/exp/cmd/gorelease@f062dba9d201f5ec084d25785efec05637818c00](http://golang.org/x/exp/cmd/gorelease@f062dba9d201f5ec084d25785efec05637818c00)) and we updated to the latest Go here, and it looks like the panic is related to changes in Go Std library.

I've run `go install golang.org/x/exp/cmd/gorelease@latest` and then `gorelease -base v0.2.3` no longer panics, so will proceed with release.

**Pull request merged**
